# Generated by Django 5.1.6 on 2025-06-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0002_alter_bid_bid_amount_alter_bid_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_amount',
            field=models.DecimalField(decimal_places=0, max_digits=25),
        ),
    ]
