# Generated by Django 5.1.6 on 2025-06-21 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0003_alter_bid_bid_amount'),
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bid',
            table=None,
        ),
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('HELD', 'Đang giữ'), ('REFUNDED', 'Đã hoàn trả'), ('TRANSFERRED', 'Đã chuyển')], default='HELD', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrows', to='items.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bids',
            },
        ),
    ]
