# Generated by Django 5.1.6 on 2025-06-22 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0004_alter_bid_table_escrow'),
        ('items', '0001_initial'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='escrow',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_transaction', to='bidding.escrow'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to='items.item'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='payment_due_date',
            field=models.DateTimeField(blank=True, help_text='Hạn chót thanh toán', null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
